server:
   port: 8761
spring:
  application:
   name: tx-manager
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/html/
    suffix: .html
  redis:
    password: foobaredbbexONE123
    sentinel:
       master: mymaster
       nodes:
             - 192.168.1.91:26379
             - 192.168.1.92:26379
             - 192.168.1.93:26379
  # host: 192.168.1.91
  # port: 6379


transactionWaitMaxTime: 500
redisSaveMaxTime: 3000

tx:
  manager:
    netty :
       port: 9988
       serialize: kryo
       maxConnection: 100
       maxThreads : 16
       delayTime : 5
       heartTime : 20





